# Generated by Django 5.2.1 on 2025-05-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nordpool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(max_length=20, unique=True, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=12, max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dane z serwera',
                'verbose_name_plural': 'Dane z serwera',
                'ordering': ['-timestamp'],
            },
        ),
    ]
