# Generated by Django 5.2.1 on 2025-05-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nordpool', '0002_serverdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdata',
            name='server_id',
            field=models.CharField(max_length=20, verbose_name='ID'),
        ),
    ]
