# Generated by Django 5.2.1 on 2025-05-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nordpool', '0003_alter_serverdata_server_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_id_1', models.CharField(max_length=20)),
                ('source_id_2', models.CharField(max_length=20)),
                ('source_value_1', models.DecimalField(decimal_places=12, max_digits=20)),
                ('source_value_2', models.DecimalField(decimal_places=12, max_digits=20)),
                ('calculated_value', models.DecimalField(decimal_places=12, max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wynik obliczenia',
                'verbose_name_plural': 'Wyniki obliczeń',
                'ordering': ['-timestamp'],
            },
        ),
    ]
