# Generated by Django 5.2.1 on 2025-05-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nordpool', '0004_calculatedresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatedBattery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.DecimalField(decimal_places=12, max_digits=20)),
                ('current_charge', models.DecimalField(decimal_places=12, default=0, max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
