# Generated by Django 5.2.1 on 2025-05-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nordpool', '0005_simulatedbattery'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatedSolarAndGridPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solar_power', models.DecimalField(decimal_places=12, default=0, max_digits=20)),
                ('grid_power', models.DecimalField(decimal_places=12, default=0, max_digits=20)),
                ('usage', models.DecimalField(decimal_places=12, default=0, max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
