# Generated by Django 5.2.1 on 2025-05-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nordpool', '0006_simulatedsolarandgridpower'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('battery_level_before', models.DecimalField(decimal_places=12, max_digits=20)),
                ('battery_percentage_before', models.DecimalField(decimal_places=2, max_digits=5)),
                ('battery_level_after', models.DecimalField(decimal_places=12, max_digits=20)),
                ('battery_percentage_after', models.DecimalField(decimal_places=2, max_digits=5)),
                ('solar_power', models.DecimalField(decimal_places=12, max_digits=20)),
                ('grid_power', models.DecimalField(decimal_places=12, max_digits=20)),
                ('usage', models.DecimalField(decimal_places=12, max_digits=20)),
                ('surplus', models.DecimalField(decimal_places=12, max_digits=20)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('decision', models.CharField(max_length=255)),
                ('decision_reason', models.TextField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
